### PR TITLE
remove inconsistencies

### PR DESCRIPTION
**Pull request by patrickhilker**
There are several minor inconsistencies in the documentation which make it hard to machine-read it. :-)

### CODE REVIEW

**Comment by d4sc** [comment]
Hi Patrick, thanks for your contribution! Unfortunately I have to close your PR:

we left the PENDING parameter out of the properties table on purpose as we do not consider it as a "return property". It is similar to the response CODE / DESCRIPTION and gives you information about the executed transaction.
To make it more clear, take a look at the below example response:

[RESPONSE]
CODE = 200
DESCRIPTION = Command completed successfully
PENDING = 1
PROPERTY[DOMAIN][0] = test.com
EOF

-> Only parameters that are included in the response as "PROPERTY[XXX][X] = XXX" are considered as return properties and show up in the table.

The rest of your proposed changes are reflected in the latest commit to the master.

Cheers,
Daniel

**Comment by patrickhilker** [comment]
Hello Daniel, I'm glad I could help! Can you think of any way to document the PENDING field in a machine-readable way? We are currently stumbling over it.

We also have a problem with the USER/ORDER/EXECUTEORDER command, because there is no information about which properties the response can have. Can this be documented somehow?

**Comment by d4sc** [comment]
To find out for which commands "PENDING=1" might be included in the response you could just match for the string "NOTE: The response might include the parameter 'PENDING = 1'" for now. We will look into this and try to find a way of including that information which is easier to parse.

Regarding the ExecuteOrder command: We haven't included any explicit return properties into the documentation as the return properties always depend on the kind of order that's being executed.
E.g. an ExecuteOrder command that executes a RenewDomain order can have all the return properties of a RenewDomain command, if an order gets executed for an AddDomain command all the return properties of the AddDomain command can get returned. So as a result the ExecuteOrder command can have a range of different return properties from other commands, listing them explicitly would have not made sense for us.

**Comment by patrickhilker** [comment]
What is the recommended way to check if pending is set? There is no special method for it in the node sdk.

**Comment by KaiSchwarz-cnic** [comment]
Dear @patrickhilker, thanks for getting in touch with us. I will work on an implementation of this in node-sdk. You may add yourself as watcher/follower to the node-sdk repository, to get updated when things are released.

**Comment by patrickhilker** [comment]
Awesome, thank you! :-)

**Comment by KaiSchwarz-cnic** [comment]
@patrickhilker give v5.5.0 of our node-sdk a try. got already auto-published on npm.

```javascript
const apiconnector = require('@hexonet/ispapi-apiconnector')
const cl = new apiconnector.APIClient()
//... apply your credential config etc.
const r = await cl.request(mycommand);
if (r.isPending()){
  console.log('operation is still pending');
} else {
  console.log('operation has finished');
}
```

give it a try.

**Pull request closed without merging**
